import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.183.2/build/three.module.js';
window.THREE=THREE;
const $=id=>document.getElementById(id);
let scene,camera,portal,ready=false,starting=false,placed=false,lastMetrics=0;
const WIDTH=1.35,HEIGHT=2.05,inversePortal=new THREE.Matrix4();
const clipUniforms={portalInverse:{value:inversePortal},portalCamera:{value:new THREE.Vector3()}};
function clipMaterial(material){material.onBeforeCompile=shader=>{Object.assign(shader.uniforms,clipUniforms);shader.vertexShader='varying vec3 portalWorld;\n'+shader.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nportalWorld=(modelMatrix*vec4(transformed,1.0)).xyz;');shader.fragmentShader='uniform mat4 portalInverse; uniform vec3 portalCamera; varying vec3 portalWorld;\n'+shader.fragmentShader.replace('void main() {',`void main(){vec3 point=(portalInverse*vec4(portalWorld,1.0)).xyz;vec3 eye=portalCamera;if(eye.z<=0.01||point.z>=0.0)discard;float t=eye.z/(eye.z-point.z);vec3 aperture=mix(eye,point,t);if(abs(aperture.x)>.675||aperture.y<0.0||aperture.y>2.05)discard;`);};material.customProgramCacheKey=()=> 'portal-aperture-v10';return material;}
function bowedPlane(w,h,bow=.08){const g=new THREE.PlaneGeometry(w,h,28,14),p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i)/(w*.5),y=p.getY(i)/(h*.5);p.setZ(i,bow*(1-x*x)+.018*Math.sin(x*9+y*5));}g.computeVertexNormals();return g;}
async function build(){
 scene.add(new THREE.HemisphereLight(0xe8eee8,0x353b2e,1.5));const sun=new THREE.DirectionalLight(0xfff0d8,1.5);sun.position.set(-4,8,3);scene.add(sun);
 portal=new THREE.Group();portal.visible=false;scene.add(portal);const add=(g,m,x=0,y=0,z=0)=>{const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.renderOrder=2;portal.add(o);return o;};
 const loader=new THREE.TextureLoader();const names=['krapina-environment-v7.jpg','kling-forest-v10.webp','kling-cave-v10.webp','kling-foliage-v10.webp','kling-ground-v10.jpg'];const [back,forest,cave,foliage,ground]=await Promise.all(names.map(n=>loader.loadAsync('assets/'+n)));
 for(const t of [back,forest,cave,foliage,ground]){t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;}
 ground.wrapS=ground.wrapT=THREE.RepeatWrapping;ground.repeat.set(1.1,2.15);
 const baseW=5.2,baseH=baseW*872/1600,eyeY=1.4,baseZ=-5.5;
 function layer(tex,z,opacity=1,bow=.06){const scale=(eyeY-z)/(eyeY-baseZ),w=baseW*scale,h=baseH*scale,y=eyeY+(baseH*.5-eyeY)*scale;const mat=clipMaterial(new THREE.MeshBasicMaterial({map:tex,transparent:tex!==back,alphaTest:tex===back?0:.025,depthWrite:tex===back,opacity,side:THREE.DoubleSide}));return add(bowedPlane(w,h,bow),mat,0,y,z);}
 layer(back,baseZ,1,.03);layer(forest,-4.72,.98,.07);layer(cave,-3.55,1,.18);layer(foliage,-2.72,1,.11);
 const floorGeo=new THREE.PlaneGeometry(8,8,30,30);floorGeo.rotateX(-Math.PI/2);const fp=floorGeo.attributes.position;for(let i=0;i<fp.count;i++)fp.setY(i,-.035+.018*Math.sin(fp.getX(i)*2.4+fp.getZ(i)));floorGeo.computeVertexNormals();const floor=add(floorGeo,clipMaterial(new THREE.MeshStandardMaterial({map:ground,color:0xaeb3a4,roughness:1})),0,0,-3.35);floor.material.polygonOffset=true;floor.material.polygonOffsetFactor=1;
 const dark=clipMaterial(new THREE.MeshBasicMaterial({color:0x080b08,transparent:true,opacity:.58,side:THREE.DoubleSide}));add(bowedPlane(1.15,1.25,.25),dark,1.05,1.25,-3.66);
 const frameMat=new THREE.MeshStandardMaterial({color:0x68736d,roughness:.9});for(const x of [-WIDTH/2-.045,WIDTH/2+.045]){const p=new THREE.Mesh(new THREE.BoxGeometry(.09,HEIGHT+.09,.12),frameMat);p.position.set(x,HEIGHT/2,.025);p.renderOrder=3;portal.add(p);}const top=new THREE.Mesh(new THREE.BoxGeometry(WIDTH+.18,.09,.12),frameMat);top.position.set(0,HEIGHT+.045,.025);top.renderOrder=3;portal.add(top);const sill=new THREE.Mesh(new THREE.BoxGeometry(WIDTH,.045,.16),frameMat);sill.position.set(0,.015,.03);sill.renderOrder=3;portal.add(sill);
 $('textures').textContent='Kling prizor razdvojen je na šumu, stijenu, vegetaciju i tlo.';
}
function syncClip(){portal.updateMatrixWorld(true);inversePortal.copy(portal.matrixWorld).invert();clipUniforms.portalCamera.value.copy(camera.position).applyMatrix4(inversePortal);}
function place(){if(!ready)return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(),camera);const hit=new THREE.Vector3(),found=ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),hit);if(!found||hit.distanceTo(camera.position)>5||hit.distanceTo(camera.position)<.5){$('status').textContent='Usmjeri sredinu kamere prema podu 1–3 m ispred sebe pa postavi otvor.';return;}portal.position.copy(hit);portal.rotation.set(0,Math.atan2(camera.position.x-hit.x,camera.position.z-hit.z),0);portal.visible=true;placed=true;syncClip();$('place').hidden=true;$('reset').hidden=false;$('status').textContent='Otvor postavljen. Pomakni se malo lijevo/desno i provjeri dubinu slojeva.';}
function fail(error){starting=false;$('intro').hidden=false;$('hud').hidden=true;$('start').disabled=false;$('start').textContent='Pokušaj ponovno';$('support').textContent='XR8 nije pokrenut: '+(error?.message||String(error));}
const pipeline={name:'isolated-pleistocene-portal-xr8-v10',onStart:async({canvas})=>{({scene,camera}=XR8.Threejs.xrScene());camera.position.set(0,1.4,0);XR8.XrController.updateCameraProjectionMatrix({origin:camera.position,facing:camera.quaternion});document.body.className='ar';$('intro').hidden=true;$('hud').hidden=false;$('place').disabled=true;$('status').textContent='Kamera radi. Učitavam slojeviti Kling prizor…';try{await build();}catch(e){fail(new Error('Učitavanje prizora: '+e.message));return;}ready=true;starting=false;$('place').disabled=false;$('status').textContent='Polako pogledaj oko sebe, naciljaj pod i postavi otvor.';canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});},onUpdate:()=>{if(!ready)return;if(placed)syncClip();const now=performance.now();if(now-lastMetrics>500){lastMetrics=now;$('metrics').textContent='Sustav: XR8 SLAM · v10\nPrizor: Kling 2.5D slojevi\nPoložaj: '+camera.position.toArray().map(x=>x.toFixed(2)).join(' / ')+'\nOtvor: '+(placed?'fiksiran':'čeka postavljanje');}},onException:fail};
async function start(){if(starting)return;starting=true;$('start').disabled=true;$('support').textContent='Pokrećem XR8 kameru…';try{XR8.XrController.configure({disableWorldTracking:false});XR8.addCameraPipelineModules([XR8.GlTextureRenderer.pipelineModule(),XR8.Threejs.pipelineModule(),XR8.XrController.pipelineModule(),LandingPage.pipelineModule(),XRExtras.FullWindowCanvas.pipelineModule(),XRExtras.Loading.pipelineModule(),XRExtras.RuntimeError.pipelineModule(),pipeline]);await XR8.run({canvas:$('camerafeed')});}catch(e){fail(e);}}
$('start').addEventListener('click',start);$('place').addEventListener('click',place);$('reset').addEventListener('click',()=>{portal.visible=false;placed=false;$('place').hidden=false;$('reset').hidden=true;$('status').textContent='Naciljaj novi položaj na podu pa postavi otvor.';});$('exit').addEventListener('click',()=>location.reload());function loaded(){if(window.XR8&&window.XRExtras&&window.LandingPage){$('start').disabled=false;$('start').textContent='Pokreni XR8 kameru';$('support').textContent='Otvori u Chromeu i dopusti kameru. Ova verzija ne traži ARCore.';}}window.addEventListener('xrloaded',loaded);loaded();setTimeout(()=>{if($('start').disabled&&!starting)$('support').textContent='XR8 se nije učitao. Provjeri vezu i osvježi stranicu.';},20000);
